baseURL = "https://www.yaxit.ml"
title   = "Andrea's Den"
languageCode = "en-us"
theme = "hello-friend-ng"

paginate = 10
enableRobotsTXT = true
enableEmoji     = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Andrea Ronco"

[params]
  customCSS = ["/css/custom.css"]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  description = "Andrea Ronco"
  keywords = "homepage, blog"

  enableSharingButtons = true

  # Subtitle for home
  homeSubtitle = "Electrical Engineer // Master Student @ ETH Zürich"
  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/" 
  
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/theyaxit"

  [[params.social]]
    name = "email"
    url  = "mailto:andr.ronco@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/Yaxit/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/andrea-ronco/"

#  [[params.social]]
#    name = "stackoverflow"
#    url  = "https://www.stackoverflow.com/"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
  [[menu.main]]
    identifier = "cv"
    name       = "Curriculum Vitae"
    url        = "cv/"
